control_configurations:
  - name: "watch"
    components:
    - {description: "", hardware_interface: "intera_hw", controller: "js_pub"}
  - name: "plan"
    components:
    - {description: "", hardware_interface: "intera_hw", controller: "js_pub"}
    - {description: "", hardware_interface: "intera_hw", controller: "thor_planner"}

  - name: "joint_teach_teleop_cfg"
    components:
      - description: ""
        hardware_interface: "intera_hw"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "intera_hw"
        controller        : "joint_teach_teleop_ctrl"
  - name: "cart_teach_teleop_cfg"
    components:
      - description: ""
        hardware_interface: "intera_hw"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "intera_hw"
        controller        : "cart_teleop_ctrl"

  - name: "cart_impedance_control"
    components:
      - description: ""
        hardware_interface: "intera_hw"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "intera_hw"
        controller        : "cart_impedance_ctrl"


intera_hw:
  type: "itia/control/InteraHwIfaceNodelet"
  joint_names:
  - right_j0
  - right_j1
  - right_j2
  - right_j3
  - right_j4
  - right_j5
  - right_j6

  remap_source_args:
  - "/intera_hw/thor_planner/follow_joint_trajectory/cancel"
  - "/intera_hw/thor_planner/follow_joint_trajectory/feedback"
  - "/intera_hw/thor_planner/follow_joint_trajectory/goal"
  - "/intera_hw/thor_planner/follow_joint_trajectory/result"
  - "/intera_hw/thor_planner/follow_joint_trajectory/status"
  remap_target_args:
  - "/sawyer/follow_joint_trajectory/cancel"
  - "/sawyer/follow_joint_trajectory/feedback"
  - "/sawyer/follow_joint_trajectory/goal"
  - "/sawyer/follow_joint_trajectory/result"
  - "/sawyer/follow_joint_trajectory/status"

  feedback_joint_state_topic: "/robot/joint_states"
  command_joint_state_topic: "/robot/limb/right/joint_command"
  sampling_period: 0.005
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_messages: 150 #default 50 causes errors

  js_pub:
    type:         ros/control/JointStatePublisher
    controlled_joint:
    - right_j0
    - right_j1
    - right_j2
    - right_j3
    - right_j4
    - right_j5
    - right_j6

  joint_teach_teleop_ctrl:
    type: "itia/control/JointTeleopController"
    controlled_joints:
    - right_j0
    - right_j1
    - right_j2
    - right_j3
    - right_j4
    - right_j5
    - right_j6

  cart_teleop_ctrl:
    type: "itia/control/CartTeleopController"
    base_link: "right_arm_base_link"
    tool_link: "right_hand"
    controlled_joints:
    - right_j0
    - right_j1
    - right_j2
    - right_j3
    - right_j4
    - right_j5
    - right_j6

  thor_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - right_j0
    - right_j1
    - right_j2
    - right_j3
    - right_j4
    - right_j5
    - right_j6
    spline_order: 2

  cart_impedance_ctrl:
    type: "itia/control/CartImpedanceController"
    controlled_joint:
    - right_j0
    - right_j1
    - right_j2
    - right_j3
    - right_j4
    - right_j5
    - right_j6
    base_frame: "right_arm_base_link"
    tool_frame: "right_hand"
    sensor_frame: "right_hand"
    inertia: [80,80,80,3,3,3]
    stiffness: [0,0,0,25,25,25]
    damping: [350,350,350,20,20,20]
    wrench_deadband: [2,2,2,2,2,2]
    joint_acc_deadband: [0.1,0.1,0.1,0.1,0.1,0.1,0.1]
    # joint_target_topic: "/joint_impedance_pos_target"
    external_wrench_topic: "/robot/limb/right/wrench"
    scaling_in_topic: "/fuzzy_scale_out"
    scaling_out_topic: "/fuzzy_scale_in"
    cart_velocity_limit: 1
    cart_acceleration_limit: 3.0
    cart_force_limit: 100.0

# impedance_hi:
#   type: "itia/control/TopicHwIfaceNodelet"
#   joint_names:
#   - right_j0
#   - right_j1
#   - right_j2
#   - right_j3
#   - right_j4
#   - right_j5
#   - right_j6
#   #allowed_controller_types:
#   #- "controller_type1"
#   feedback_joint_state_topic: "/robot/joint_states"
#   command_joint_state_topic: "/ur5/joint_pos_target"
#   sampling_period: 0.008
#   diagnostic_period: 0.1
#   feedback_joint_state_timeout: 20

#   cart_impedance_ctrl:
#     type: "itia/control/CartImpedanceController"
#     controlled_joint:
#     - ur5_shoulder_pan_joint
#     - ur5_shoulder_lift_joint
#     - ur5_elbow_joint
#     - ur5_wrist_1_joint
#     - ur5_wrist_2_joint
#     - ur5_wrist_3_joint
#     base_frame: "ur5_base_link"
#     tool_frame: "ur5_tool0"
#     sensor_frame: "ur5_tool0"
#     inertia: [30,30,30,3,3,3]
#     stiffness: [120,120,120,25,25,25]
#     damping: [105,105,105,20,20,20]
#     wrench_deadband: [1,1,1,1,1,1]
#     joint_acc_deadband: [0.1,0.1,0.1,0.1,0.1,0.1]
#     joint_target_topic: "/joint_impedance_pos_target"
#     external_wrench_topic: "/robotiq_ft_wrench"
#     scaling_in_topic: "/fuzzy_scale_out"
#     scaling_out_topic: "/fuzzy_scale_in"
#     cart_velocity_limit: 1
#     cart_acceleration_limit: 3.0
#     cart_force_limit: 100.0
